### ISSUE TITLE
Clipboard does not work in Zazu 0.6.0

### ISSUE THREAD

**Issue by albert-k** [tinytacoteam/zazu-clipboard#21]
Search fails with the error in `Plugin debugger`:

```
ERROR: [14:33:04] [tinytacoteam/zazu-clipboard :searcher]
Script failed
{
  "block": "searcher",
  "error": "{ query: '',\n  error:\n   { Error [TypeError]: ago is not a function\n       at /Users/albert.kimyagarov/.zazu/plugins/tinytacoteam/zazu-clipboard/src/lib/present.js:14:22\n       at Array.map (<anonymous>)\n       at present (/Users/xyz/.zazu/plugins/tinytacoteam/zazu-clipboard/src/lib/present.js:9:19)\n       at /Users/xyz/.zazu/plugins/tinytacoteam/zazu-clipboard/src/search.js:9:28 message: 'ago is not a function', name: 'TypeError' } }",
  "level": "error",
  "message": "Script failed",
  "plugin": "tinytacoteam/zazu-clipboard",
  "time": "2019-08-19T11:33:04.699Z"
}
```

```
App Environment: production
App Version: 0.6.0
Electron Version: 5.0.4
Node Version: 12.0.0
Chrome Version: 73.0.3683.121
```

**Comment by AntonShumin** [comment]
I am having the same ago is not a function error on windows 10

**Comment by bayleedev** [comment]
Fixed by #22
